<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b1276f3f-87d5-4fb5-b4f1-7d3ee374ab63</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_manage_apps</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/section[1]/nav[1]/div[1]/div[1]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="aui-navgroup-primary"] &gt; [class="aui-nav"] &gt; li:nth-child(4) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Manage apps')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Manage apps</value>
        <webElementGuid>73eb81ab-4175-432c-98a8-2030c343be27</webElementGuid>
    </webElementProperties>
</WebElementEntity>