<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f0fa49f5-4cbd-481c-b5d9-d5daa3d3ab70</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_general_configuration</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/section[1]/div[2]/div[1]/div[1]/nav[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#general_configuration</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'general_configuration') and equals(@text,'General configuration')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>general_configuration</value>
        <webElementGuid>73eb81ab-4175-432c-98a8-2030c343be27</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>General configuration</value>
        <webElementGuid>73eb81ab-4175-432c-98a8-2030c343be27</webElementGuid>
    </webElementProperties>
</WebElementEntity>