<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e7a06f94-bbe8-41a3-8fd8-096444bc3346</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_global_if_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/nav[1]/div[1]/div[1]/ul[1]/li[6]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#global-if-link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'global-if-link') and equals(@text,'Issue forms')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>global-if-link</value>
        <webElementGuid>73eb81ab-4175-432c-98a8-2030c343be27</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Issue forms</value>
        <webElementGuid>73eb81ab-4175-432c-98a8-2030c343be27</webElementGuid>
    </webElementProperties>
</WebElementEntity>