<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>29caa72f-936c-4ff4-a486-3371c6f61b66</elementGuidId>
    <imagePath></imagePath>
    <name>em_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/form[1]/div[2]/div[1]/ul[1]/li[1]/span[1]/em[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>em</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>